# Generated by Django 5.1.3 on 2025-03-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=255)),
                ('telefone_funcionario', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_funcionario', models.CharField(blank=True, max_length=255, null=True)),
                ('funcao_funcionario', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_funcionario', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('tipo_funcionario', models.CharField(choices=[('Quadro', 'Quadro'), ('Extra Quadro', 'Extra Quadro')], default='Quadro', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.IntegerField()),
                ('tipo_de_sala', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_saida_horario', models.DateTimeField()),
                ('chaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keylink.chave')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keylink.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_entrada_horario', models.DateTimeField()),
                ('chaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keylink.chave')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keylink.funcionario')),
                ('registro_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keylink.registrosaida')),
            ],
        ),
        migrations.AddField(
            model_name='chave',
            name='salas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Keylink.sala'),
        ),
    ]
