# Generated by Django 5.1.3 on 2025-04-26 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id_chaves', models.AutoField(db_column='id_chaves', primary_key=True, serialize=False)),
                ('numero_chave', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
                'db_table': 'chaves',
                'ordering': ['numero_chave'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id_funcionario', models.AutoField(db_column='id_funcionario', primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=255)),
                ('usuario_funcionario', models.CharField(max_length=255, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('telefone_funcionario', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_funcionario', models.CharField(blank=True, max_length=255, null=True)),
                ('funcao_funcionario', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_funcionario', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('tipo_funcionario', models.CharField(choices=[('Quadro', 'Quadro'), ('Extra Quadro', 'Extra Quadro')], default='Quadro', max_length=20)),
                ('tipo_usuario', models.CharField(choices=[('usuario', 'Usuário'), ('admin', 'Administrador')], default='usuario', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionarios',
                'ordering': ['nome_funcionario'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSaida',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('registro_saida_horario', models.DateTimeField()),
                ('chaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_saida', to='Keylink.chave')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_saida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id_registro_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('registro_entrada_horario', models.DateTimeField()),
                ('chaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to='Keylink.chave')),
                ('registro_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to='Keylink.registrosaida')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chave',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaves_utilizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_funcionario__in', ['Quadro', 'Extra Quadro'])), name='tipo_funcionario_valido'),
        ),
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_usuario__in', ['usuario', 'admin'])), name='tipo_usuario_valido'),
        ),
    ]
