# Generated by Django 5.1.3 on 2025-03-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Keylink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='usuario_funcionario',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
