# Generated by Django 5.1.3 on 2025-03-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Keylink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSaida',
            fields=[
                ('id_registro', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('registro_saida_horario', models.DateTimeField()),
                ('chaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_saida', to='Keylink.chave')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_saida', to='Keylink.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id_registro_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('registro_entrada_horario', models.DateTimeField()),
                ('chaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to='Keylink.chave')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to='Keylink.funcionario')),
                ('registro_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to='Keylink.registrosaida')),
            ],
        ),
    ]
