# Generated by Django 5.2 on 2025-04-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Keylink', '0002_funcionario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='usuario_funcionario',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
