# Generated by Django 5.1.3 on 2025-04-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Keylink', '0002_registrosaida_registroentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
