# Generated by Django 5.1.3 on 2025-03-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Keylink', '0002_funcionario_usuario_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='id',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registroentrada',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registrosaida',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='id',
        ),
        migrations.AddField(
            model_name='chave',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chave',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chave',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chave',
            name='id_chaves',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chave',
            name='numero_chave',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_funcionario',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='id_registro_entrada',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrosaida',
            name='id_registro',
            field=models.CharField(default=1, max_length=45, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='id_sala',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chave',
            name='salas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to='Keylink.sala'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_funcionario',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_funcionario',
            field=models.CharField(default='Quadro', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroentrada',
            name='chaves',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to='Keylink.chave'),
        ),
        migrations.AlterField(
            model_name='registroentrada',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to='Keylink.funcionario'),
        ),
        migrations.AlterField(
            model_name='registroentrada',
            name='registro_saida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_entrada', to='Keylink.registrosaida'),
        ),
        migrations.AlterField(
            model_name='registrosaida',
            name='chaves',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_saida', to='Keylink.chave'),
        ),
        migrations.AlterField(
            model_name='registrosaida',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_saida', to='Keylink.funcionario'),
        ),
    ]
