# Generated by Django 5.1.3 on 2025-03-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Keylink', '0003_remove_chave_id_remove_funcionario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosaida',
            name='chaves',
        ),
        migrations.RemoveField(
            model_name='registrosaida',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='chave',
            name='salas',
        ),
        migrations.DeleteModel(
            name='RegistroEntrada',
        ),
        migrations.DeleteModel(
            name='RegistroSaida',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
