# Generated by Django 5.1.3 on 2025-04-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Keylink', '0003_funcionario_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_funcionario',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario_funcionario',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
