# Generated by Django 5.1.3 on 2025-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Keylink', '0004_remove_registrosaida_chaves_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'ordering': ['numero_chave'], 'verbose_name': 'Chave', 'verbose_name_plural': 'Chaves'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome_funcionario'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_funcionario__in', ['Quadro', 'Extra Quadro'])), name='tipo_funcionario_valido'),
        ),
        migrations.AlterModelTable(
            name='chave',
            table='chaves',
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionarios',
        ),
    ]
